### ISSUE TITLE
How to cite this implementation?

### ISSUE THREAD

**Issue by KeAWang** [hjmshi/PyTorch-LBFGS#11]
If we would like to refer to this implementation of `FullBatchLBFGS` in a publication, is there a specific paper that we should cite? If so, would it be possible for the README to include a bibtex for this purpose?

**Comment by hjmshi** [comment]
For full batch L-BFGS, it is sufficient to refer to the original L-BFGS papers:

Liu, Dong C., and Jorge Nocedal. "On the Limited Memory BFGS Method for Large Scale Optimization." Mathematical Programming 45.1-3 (1989): 503-528.
Nocedal, Jorge. "Updating Quasi-Newton Matrices With Limited Storage." Mathematics of Computation 35.151 (1980): 773-782.

These are references 4 and 5 in the README.
