### ISSUE TITLE
Some confusion about the code.

### ISSUE THREAD

**Issue by yangorwell** [hjmshi/PyTorch-LBFGS#12]
When I use the Powell damping to hold the PSD property of the metric matrix, I find the Bs update are written as "Bs.copy_(g_Sk.mul(-t))". Is it right?

**Comment by hjmshi** [comment]
Hi, thanks for taking a look at the code! 

Powell damping in the code actually occurs in the modification of y in this part of the code: https://github.com/hjmshi/PyTorch-LBFGS/blob/e79e7d96b67a3c8034b3dd3864f59b5b20b4733a/functions/LBFGS.py#L384-L389. 

Bs is explicitly computed by noting that $x_{k + 1} = x_k - t H_k g_{S_k}, so B_k s_k = B_k (x_{k + 1} - x_k) = -t B_k H_k g_{S_k} = -t g_{S_k}$. Note that we never explicitly compute B. 

Please let me know if this helps clarify things!

**Comment by yangorwell** [comment]
Thanks for your prompt response!  This solve my problem!
