### ISSUE TITLE
Error due to to .view operation on gradients

### ISSUE THREAD

**Issue by adityamnk** [hjmshi/PyTorch-LBFGS#17]
I am only running on CPU right now, but will move on to powerful GPUs once I get it to work on CPU. I am using pytorch 1.6.0.

I have a class for iteratively solving an inverse problem. This class uses your LBFGS optimizer, specifically, with the following parameters -
self.optimizer = FullBatchLBFGS(self.model.parameters(), lr=1, history_size=10, line_search='Wolfe', debug=True)

I use the following code for optimization based on your examples - 
options = {'closure': closure, 'current_loss': self.loss_fn(self.model(), data), 'eta': 2,'max_ls': 100, 'interpolate': True, 'inplace': False}
obj, grad, lr, backtracks, clos_evals, grad_evals, desc_dir, fail = self.optimizer.step(options=options)

However, I get the following error -
  File "/Users/mohan3/Desktop/Devs/Phase_Img/Code/phasetorch/phasetorch/pret.py", line 59, in run
    obj, grad, lr, backtracks, clos_evals, grad_evals, desc_dir, fail = self.optimizer.step(
  File "/Users/mohan3/Desktop/Devs/Phase_Img/Code/phasetorch/phasetorch/LBFGS.py", line 1107, in step
    return self._step(p, grad, options=options)
  File "/Users/mohan3/Desktop/Devs/Phase_Img/Code/phasetorch/phasetorch/LBFGS.py", line 872, in _step
    g_new = self._gather_flat_grad()
  File "/Users/mohan3/Desktop/Devs/Phase_Img/Code/phasetorch/phasetorch/LBFGS.py", line 250, in _gather_flat_grad
    view = p.grad.data.view(-1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

It seems like there is a problem with using .view within the file LBFGS.py. The error message suggests to try using reshape. Is it possible to re-implement this method using torch.reshape? Just replacing the .view with torch.reshape seems to result in a new error message "Not a descent direction!".

**Comment by hjmshi** [comment]
Thanks for trying PyTorch-LBFGS! I think this error has to do with how the tensor is being stored in memory. The code should work if you call reshape instead of view or call contiguous() before view. 

The new error message indicates that the computed gradient dot product with the search direction is not less than 0, meaning the search direction is not a descent direction with respect to the computed gradient. Is this occurring at the beginning of your run or after some iterations?

**Comment by adityamnk** [comment]
Yes. Calling contiguous on the trainable tensor does solve the .view problem. 

However, I still get "Not a descent direction" error and the loss does not seem to have reduced. See below a standalone code that you can run. The below code mimics my use case. I may have made a mistake when invoking LBFGS. I use python 3.8 and pytorch 1.6. 

```
import torch
import numpy as np
from phasetorch.LBFGS import FullBatchLBFGS


class ModelTest(torch.nn.Module):
    def __init__(self, N_y, N_x, d):
        super(ModelTest, self).__init__()
        tran = np.random.randn(d, 1, N_y, N_x, 2).astype(
            np.double, order='C')
        self.transform = torch.tensor(
            tran, dtype=torch.double, requires_grad=False)

    def forward(self, x):
        x = torch.fft(x, signal_ndim=2)
        y_real = x[:, :, :, :, 0]*self.transform[:, :, :, :, 0] - \
            x[:, :, :, :, 1]*self.transform[:, :, :, :, 1]
        y_imag = x[:, :, :, :, 0]*self.transform[:, :, :, :, 1] + \
            x[:, :, :, :, 1]*self.transform[:, :, :, :, 0]
        x = torch.stack((y_real, y_imag), dim=-1)
        x = torch.ifft(x, signal_ndim=2)
        x = x[:, :, :, :, 0]*x[:, :, :, :, 0]+x[:, :, :, :, 1]*x[:, :, :, :, 1]
        return x


class ModelTestOpt(torch.nn.Module):
    def __init__(self, init, N_y, N_x, d):
        super(ModelTestOpt, self).__init__()
        self.model = ModelTest(N_y, N_x, d)
        # self.rec = torch.nn.Parameter(torch.tensor(
        #    init, dtype=torch.double, requires_grad=True))
        self.rec = torch.nn.Parameter(torch.from_numpy(init).contiguous())

    def forward(self):
        return self.model(self.rec)


class Sim_Algo:
    def __init__(self, N_y, N_x, d):
        self.model = ModelTest(N_y, N_x, d)

    def run(self, data):
        data = torch.tensor(data, dtype=torch.double, requires_grad=False)
        new_shape = (-1, data.size(-4), data.size(-3),
                     data.size(-2), data.size(-1))
        data = torch.reshape(data, new_shape)
        return self.model(data)


class Iter_Algo:
    def __init__(self, init, N_y, N_x, d):
        init = init.reshape(
            (-1, init.shape[-4], init.shape[-3], init.shape[-2], init.shape[-1]))
        self.model = ModelTestOpt(init, N_y, N_x, d)
        self.loss_fn = torch.nn.MSELoss(reduce=True, reduction='mean')
        self.optimizer = FullBatchLBFGS(
            self.model.parameters(), lr=1, history_size=10, line_search='Wolfe', debug=True)

    def run(self, data):
        data = torch.tensor(data, dtype=torch.double, requires_grad=False)

        def closure():
            self.optimizer.zero_grad()
            data_pred = self.model()
            loss = self.loss_fn(data_pred, data)
            return loss

        loss = self.loss_fn(self.model(), data).detach().numpy()
        print('Init loss: ', loss)

        loss = self.loss_fn(self.model(), data).detach().numpy()
        print('Init loss: ', loss)
        options = {'closure': closure, 'current_loss': self.loss_fn(self.model(
        ), data), 'eta': 2, 'max_ls': 100, 'interpolate': True, 'inplace': False}
        obj, grad, lr, backtracks, clos_evals, grad_evals, desc_dir, fail = self.optimizer.step(
            options=options)

        loss = self.loss_fn(
            self.model(), data).detach().numpy()
        print('Final loss: ', loss)

        rec = self.model.rec.detach().numpy()
        return rec, loss


N_y, N_x = 72, 96
d = 3

init = np.random.randn(1, N_y, N_x, 2).astype(dtype=np.double, order='C')
transform = np.random.randn(d, N_y, N_x, 2).astype(dtype=np.double, order='C')

simtor = Sim_Algo(N_y, N_x, d)
data = simtor.run(init)

# Comment next three lines to prevent error
init = np.random.randn(1, N_y, N_x)+1j*np.random.randn(1, N_y, N_x)
init = np.stack((np.real(init), np.imag(init)),
                axis=0).astype(dtype=np.double, order='C')
init = np.moveaxis(init, 0, -1)
# Uncomment below line to prevent error
#init = np.random.randn(1, N_y, N_x, 2).astype(dtype=np.double, order='C')
solver = Iter_Algo(init, N_y, N_x, d)
solver.run(data)

```

**Comment by hjmshi** [comment]
Thanks for giving an example of your code! Could you try calling backward on your loss before your step? (In general, for the FullBatchLBFGS function, you should call backward before entering into your for loop; after this, the optimizer will call backward for you because of the Wolfe line search.)

Here's how I'd try modifying your Iter_Algo class:
```
class Iter_Algo:
    def __init__(self, init, N_y, N_x, d):
        init = init.reshape(
            (-1, init.shape[-4], init.shape[-3], init.shape[-2], init.shape[-1]))
        self.model = ModelTestOpt(init, N_y, N_x, d)
        self.loss_fn = torch.nn.MSELoss(reduce=True, reduction='mean')
        self.optimizer = FullBatchLBFGS(
            self.model.parameters(), lr=1, history_size=10, line_search='Wolfe', debug=True)

    def run(self, data):
        data = data.clone().detach()

        def closure():
            self.optimizer.zero_grad()
            data_pred = self.model()
            loss = self.loss_fn(data_pred, data)
            return loss

        self.model.zero_grad()
        loss = self.loss_fn(self.model(), data)
        loss.backward()
        print('Init loss: ', loss.detach().numpy())
        options = {'closure': closure, 'current_loss': self.loss_fn(self.model(), data), 'eta': 2, 'max_ls': 100, 'interpolate': True, 'inplace': False}
        obj, grad, lr, backtracks, clos_evals, grad_evals, desc_dir, fail = self.optimizer.step(options=options)

        loss = self.loss_fn(self.model(), data).detach().numpy()
        print('Final loss: ', loss)

        rec = self.model.rec.detach().numpy()
        return rec, loss
``` 

Please let me know if you still run into the "Not a descent direction!" after you loop over this iteration.

**Comment by adityamnk** [comment]
Sorry for the delay in replying. Thank you for your solution. The error does goes away.
